### ISSUE TITLE
sometimes it's failed to download forwarded media :]

### ISSUE THREAD

**Issue by MrCarb0n** [magneto261290/magneto-python-aria#55]
```
2020-11-25 07:12:50,397 - pyrogram.crypto.aes - INFO - Using TgCrypto
2020-11-25 07:12:51,363 - bot - INFO - Bot Started!
2020-11-25 07:13:43,979 - bot - INFO - 
2020-11-25 07:13:46,388 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyrogram/client/client.py", line 1659, in resolve_peer
    return self.storage.get_peer_by_id(peer_id)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/client/storage/sqlite_storage.py", line 108, in get_peer_by_id
    raise KeyError("ID not found: {}".format(peer_id))
KeyError: 'ID not found: -1001478941600'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/usr/src/app/bot/modules/mirror.py", line 259, in mirror
    _mirror(context.bot, update)
  File "/usr/src/app/bot/modules/mirror.py", line 225, in _mirror
    tg_downloader.add_download(reply_to, f'{DOWNLOAD_DIR}{listener.uid}/')
  File "/usr/src/app/bot/helper/mirror_utils/download_utils/telegram_downloader.py", line 88, in add_download
    _message = self.__user_bot.get_messages(message.chat.id, message.message_id)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/client/methods/messages/get_messages.py", line 101, in get_messages
    peer = self.resolve_peer(chat_id)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/client/client.py", line 1708, in resolve_peer
    self.send(
  File "/usr/local/lib/python3.8/site-packages/pyrogram/client/client.py", line 1381, in send
    r = self.session.send(data, retries, timeout)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/session/session.py", line 436, in send
    return self._send(data, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/session/session.py", line 423, in _send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 79, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ChannelInvalid: [400 CHANNEL_INVALID]: The channel parameter is invalid (caused by "channels.GetChannels")

```

**Comment by magneto261290** [comment]
Make sure these things
1. You are using bot in group. (TG file mirror works perfectly in groups)
2. Bot is admin in group.
3. You have generated string session using Bot Token (not mobile number)

**Comment by MrCarb0n** [comment]
Ohho, I made session with Cell number. thanks btw <3
