### ISSUE TITLE
ModuleNotFoundError: No module named 'appdirs'

### ISSUE THREAD

**Issue by Vincher-coder** [magneto261290/magneto-python-aria#61]
docker run mirror-bot
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 6, in <module>
    import aria2p
  File "/usr/local/lib/python3.8/site-packages/aria2p/__init__.py", line 11, in <module>
    from aria2p.api import API
  File "/usr/local/lib/python3.8/site-packages/aria2p/api.py", line 16, in <module>
    from aria2p.client import Client, ClientException
  File "/usr/local/lib/python3.8/site-packages/aria2p/client.py", line 16, in <module>
    from aria2p.utils import SignalHandler
  File "/usr/local/lib/python3.8/site-packages/aria2p/utils.py", line 15, in <module>
    from appdirs import user_config_dir
ModuleNotFoundError: No module named 'appdirs'

**Comment by nullbytes0** [comment]
put in requirements.txt
appdirs

**Comment by magneto261290** [comment]
It has been solved by merging a pull request
